classes=['Apple___Apple_scab', 'Apple___Black_rot', 'Apple___Cedar_apple_rust', 'Apple___healthy', 
         'Blueberry___healthy', 
         'Cherry_(including_sour)___Powdery_mildew', 
         'Cherry_(including_sour)___healthy', 
         'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot', 
         'Corn_(maize)___Common_rust_', 
         'Corn_(maize)___Northern_Leaf_Blight', 
         'Corn_(maize)___healthy', 
         'Grape___Black_rot', 
         'Grape___Esca_(Black_Measles)', 
         'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)', 
         'Grape___healthy', 
         'Orange___Haunglongbing_(Citrus_greening)', 
         'Peach___Bacterial_spot', 
         'Peach___healthy', 
         'Pepper,_bell___Bacterial_spot', 
         'Pepper,_bell___healthy', 
         'Potato___Early_blight', 
         'Potato___Late_blight', 
         'Potato___healthy', 
         'Raspberry___healthy', 
         'Soybean___healthy', 
         'Squash___Powdery_mildew', 
         'Strawberry___Leaf_scorch', 
         'Strawberry___healthy', 
         'Tomato___Bacterial_spot', 
         'Tomato___Early_blight', 
         'Tomato___Late_blight', 
         'Tomato___Leaf_Mold', 
         'Tomato___Septoria_leaf_spot', 
         'Tomato___Spider_mites Two-spotted_spider_mite',
         'Tomato___Target_Spot', 
         'Tomato___Tomato_Yellow_Leaf_Curl_Virus',
         'Tomato___Tomato_mosaic_virus', 
         'Tomato___healthy']

descriptionn={'Apple___Apple_scab':{"description":"A fungal infection causing olive-green to black velvety spots on leaves and fruit, leading to premature leaf drop and cracked fruit.",
                                    "Treatment":"Apply copper-based fungicides in early spring and clear away fallen leaves in autumn to prevent spore overwintering."},
              'Apple___Black_rot':{'description':"A destructive fungal disease causing frog-eye leaf spots, cankers on limbs, and a dark brown, rotting ring on fruit.",
                                   "Treatment":"Prune out dead wood and cankers during winter dormancy, and apply preventative sulfur or copper fungicides during the growing season."},
              'Apple___Cedar_apple_rust':{"description":"A striking fungus requiring both cedar and apple trees to survive, producing bright orange-yellow spots on apple leaves.",
                                          "Treatment":"Remove nearby juniper/cedar trees if possible, and apply protective fungicides (like Myclobutanil) as buds begin to open."},
              'Apple___healthy':{"description":"It means the plant is healthy",
                                 "Treatment":"No Treatment Needed"},
              'Blueberry___healthy':{"description":"It means the plant is healthy",
                                     "Treatment":"No Treatment Needed"},
              'Cherry_(including_sour)___Powdery_mildew':{"description":"A common fungal issue creating a white, powdery coating on young leaves and twigs, causing them to curl upward and distort.",
                                                          "Treatment":"Increase air circulation by pruning dense branches, and spray potassium bicarbonate or neem oil at the first sign of symptoms."},
              'Cherry_(including_sour)___healthy':{"description":"It means the plant is healthy",
                                                   "Treatment":"No Treatment Needed"},
              'Corn_(maize)___Cercospora_leaf_spot Gray_leaf_spot':{"description":"A fungal disease causing distinct, tan-to-gray rectangular spots on leaves that run parallel to the leaf veins.",
                                                                    "Treatment":"Use disease-resistant corn hybrids, rotate crops annually, and apply foliar fungicides if severe symptoms appear before tasseling."},
              'Corn_(maize)___Common_rust_':{"description":"A highly visible fungal disease producing powdery, reddish-brown pustules on both upper and lower leaf surfaces.",
                                             "Treatment":"Plant resistant hybrids early in the season and apply triazole-based fungicides if infections threaten upper leaves."},
              'Corn_(maize)___Northern_Leaf_Blight':{"description":"A fungus causing long, cigar-shaped, grayish-green lesions on leaves that eventually turn tan and cause premature drying.",
                                                     "Treatment":"Practice deep tillage to bury crop debris, rotate away from corn for a year, and apply preventative fungicides."},
              'Corn_(maize)___healthy':{"description":"The plant is very healthy",
                                        "Treatment":"No Treatment Needed"},
              'Grape___Black_rot':{"description":"A devastating fungus attacking all green parts of the vine, turning plump grapes into shriveled, hard black mummies.",
                                   "Treatment":"Prune infected vines cleanly, clear mummified berries from the soil, and spray copper fungicides from bud break until bloom."},
              'Grape___Esca_(Black_Measles)':{"description":"A complex wood-boring fungal disease causing dramatic tiger-stripe yellowing on leaves and dark spots on berry skin.",
                                              "Treatment":"Protect winter pruning wounds with a paste sealant, and remove severely infected wood or dead vines from the vineyard."}, 
              'Grape___Leaf_blight_(Isariopsis_Leaf_Spot)':{"description":"A fungal infection producing small brown spots on older leaves that merge into large, dry, dead patches.", 
                                                            "Treatment":"Ensure proper vine spacing for sunlight exposure and apply copper- or sulfur-based protective sprays post-harvest."},
              'Grape___healthy':{"description":"The gape plant is healthy",
                                 "Treatment":"No Treatment Needed"}, 
              'Orange___Haunglongbing_(Citrus_greening)':{"description": "A fatal bacterial disease spread by insects that causes blotchy, yellowing leaves and small, bitter, lopsided green fruit.",
                                                          "Treatment":"There is no cure; control the Asian citrus psyllid insect vector with insecticides and aggressively remove infected trees to save the grove."}, 
              'Peach___Bacterial_spot':{'description':"A bacterial infection causing water-soaked spots on leaves that fall out, leaving shot-holes, and pitting on the fruit.", 
                                        'Treatment':"Avoid high-nitrogen fertilizers which spark vulnerable flush growth, and apply copper sprays during the late dormant season."},
              'Peach___healthy':{"description":"The peach plant is healthy",
                                 "Treatment":"No Treatment Needed"}, 
              'Pepper,_bell___Bacterial_spot':{"description":"Causes small, raised warts on fruit and dark, water-soaked circular spots on leaves, leading to severe leaf drop.", 
                                               "Treatment":"Use pathogen-free seeds, avoid overhead sprinkler watering, and spray copper-mancozeb bactericides early in the cycle."},
              'Pepper,_bell___healthy':{"description":"The pepper plant is healthy ",
                                        "Treatment":"No Treatment Needed"}, 
              'Potato___Early_blight':{"description":"A fungal disease creating dark, concentric target-board spots on older leaves, reducing overall tuber yield.", 
                                       "Treatment":"Maintain optimal soil nutrition (especially nitrogen) and apply protective chlorothalonil or copper fungicides."},
              'Potato___Late_blight':{"description":"A historically devastating oomycete causing rapid, dark, water-soaked leaf lesions with white mold underneath during cool, wet weather.", 
                                      "Treatment":"Destroy volunteer potato plants, avoid overhead watering, and spray systemic fungicides immediately when humid weather strikes"},
              'Potato___healthy':{"description":"The potato plant is healthy",
                                  "Treatment":"No Treatment Needed"}, 
              'Raspberry___healthy':{"description":"The raspberry plant is healthy", 
                                     "Treatment":"No Treatment Needed"},
              'Soybean___healthy':{"description":"The soyabean plant is healthy",
                                   "Treatment":"No Treatmen Needed"}, 
              'Squash___Powdery_mildew':{"description":"A fungal dust covering the upper leaf surfaces in white powder, blocking sunlight and causing leaves to wither.", 
                                         "Treatment":"Plant in full sun with wide spacing, and apply preventive sulfur sprays or horticultural oils before the fungus spreads."},
              'Strawberry___Leaf_scorch':{"description":"A fungal issue causing dark purple spots on leaves that expand into large, dark brown blotches, making the leaf look scorched.", 
                                          "Treatment":"Thin out plants to lower humidity, clear away old mulch after harvest, and apply target fungicides during early spring bloom."},
              'Strawberry___healthy':{"description":"The strawberry plant is healthy",
                                      "Treatment":"No Treatment Needed"},
              'Tomato___Bacterial_spot':{"description":"A bacterial disease causing small, greasy black spots on leaves and rough, scabby lesions directly on the tomatoes.", 
                                         "Treatment":"Rotate crops with non-solanaceous plants, avoid working with wet plants, and use copper-based bactericides."},
              'Tomato___Early_blight':{"description":"A fungus showing up as concentric rings (target-like shapes) on lower leaves, causing them to yellow and fall off.", 
                                       "Treatment":"Prune lower leaves to prevent splash-zone soil contact, mulch the base, and use copper or chlorothalonil sprays."},
              'Tomato___Late_blight':{"description":"A fast-moving pathogen causing large, dark, greasy leaf lesions and firm, glossy brown rot spots on green fruit.", 
                                      "Treatment":"Immediately remove and destroy infected plants, maximize air circulation, and apply preventative fungicides during wet weather."},
              'Tomato___Leaf_Mold':{"description":"A fungal disease common in high-humidity greenhouses, creating pale green spots on upper leaves and olive-green velvety mold underneath.", 
                                    "Treatment":"Lower greenhouse humidity below 85%, space plants widely, and apply preventative anti-fungal sprays."},
              'Tomato___Septoria_leaf_spot':{"description":"A destructive fungal infection causing thousands of tiny circular spots with grey centers and dark borders on lower leaves.", 
                                             "Treatment":"Use drip irrigation to keep foliage completely dry, keep the garden weed-free, and spray copper fungicides at the first sign of spots."},
              'Tomato___Spider_mites Two-spotted_spider_mite':{"description":"Tiny pests that suck plant sap, creating fine white webbing under leaves and yellowish speckling across the foliage.",
                                                               "Treatment":"Spray the plants with a strong stream of water to knock them off, or apply insecticidal soap or neem oil underneath the leaves."},
              'Tomato___Target_Spot':{"description":"A fungus causing pinprick lesions on leaves that expand into dark brown spots with explicit concentric rings and yellow halos.", 
                                      "Treatment":"Keep plants staked and well-pruned for maximum airflow, and apply mancozeb or copper-based fungicides."},
              'Tomato___Tomato_Yellow_Leaf_Curl_Virus':{"description":"A viral infection spread by whiteflies that severely stunts growth and causes leaves to roll dramatically upward and turn yellow.",
                                                        "Treatment":"Use silver reflective mulches to repel whiteflies, install fine mesh netting, and immediately pull up infected virus-reservoir plants."},
              'Tomato___Tomato_mosaic_virus':{"description":"A highly contagious virus creating a green-and-yellow mosaic mottling pattern on leaves, stunting leaves into narrow shoestrings.", 
                                              "Treatment":"There is no chemical cure; wash hands/tools thoroughly with soap or milk before handling plants, and source certified virus-free seeds."},
              'Tomato___healthy':{"description":"The Tomato plant is healthy",
                                  "Treatment":"No Treatment Needed"}}
