import torch.nn as nn
class CNNModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.conv1=nn.Conv2d(in_channels=3,out_channels=32,kernel_size=3,stride=1,padding=1)
    self.conv2=nn.Conv2d(32,64,3,stride=1)
    self.conv3=nn.Conv2d(64,128,3)
    self.relu=nn.ReLU()
    self.pool=nn.MaxPool2d(2)
    self.flatten=nn.Flatten()
    self.gap=nn.AdaptiveAvgPool2d((1,1))
    self.batchnorm1=nn.BatchNorm2d(32)
    self.batchnorm2=nn.BatchNorm2d(64)
    # self.batchnorm3=nn.BatchNorm2d(128)
    self.dropout=nn.Dropout(0.2)
    self.fc1=nn.Linear(128,128)
    self.fc2=nn.Linear(128,38)

  def forward(self,x):
    x=self.conv1(x)
    x=self.batchnorm1(x)
    x=self.relu(x)
    x=self.pool(x)
    x=self.dropout(x)
    x=self.conv2(x)
    x=self.batchnorm2(x)
    x=self.relu(x)
    x=self.pool(x)
    x=self.dropout(x)
    x=self.conv3(x)
    # x=self.batchnorm3(x)
    x=self.relu(x)
    x=self.pool(x)
    x=self.gap(x)
    x=self.flatten(x)
    x=self.fc1(x)
    x=self.relu(x)
    x=self.fc2(x)
    return x